

# 1. Importing data

## Loading functions
```{r}
rm(list=ls())
gc()
```


```{r}
output_path <- "./output/Brains/WT_change/outliers_removed/"

output_path <- "./output/Brains/"
output_path <- "./output/Brains/outlier_removed/"

#CLN3
output_path <- "./output/Brains/CLN3/"
output_path <- "./output/Brains/CLN3/outlier_removed/"
#CLN12
output_path <- "./output/Brains/CLN12/"
output_path <- "./output/Brains/CLN12/outlier_removed/"



output_path <- paste0(output_path, "mnar_zero/")

output_path <- paste0(output_path, "mnar_MinProb/")
```


```{r}
source("../code/global_variables.R")
source("../code/00_packages.R")
source("../code/01_loading_data.R")
source("../code/03_cleaning_data.R")
source("../code/04_data_analysis.R")
```


```{r}
#import data
prot_data_brain <- readxl::read_xlsx(path = "../rawdata/20240126_ZF_brains_lfq_proteomic.xlsx")
loading_data(prot_data_brain)
prot_data_brain <- readxl::read_xlsx(path = "../rawdata/20240126_ZF_brains_lfq_proteomic_WT_Lux1_Changed")


```



# 2. Experiment desing


```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2", "lfq_wt_3","lfq_wt_4",
              "lfq_cln3_lux1_1", "lfq_cln3_lux1_2","lfq_cln3_lux1_3", "lfq_cln3_lux1_4",
              "lfq_cln3_lux2_1","lfq_cln3_lux2_2", "lfq_cln3_lux2_3", "lfq_cln3_lux2_4",
              "lfq_cln12_1","lfq_cln12_2", "lfq_cln12_3", "lfq_cln12_4")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN3_Lux1_1", "CLN3_Lux1_2", "CLN3_Lux1_3","CLN3_Lux1_4",
                       "CLN3_Lux2_1","CLN3_Lux2_2", "CLN3_Lux2_3","CLN3_Lux2_4",
                       "CLN12_1","CLN12_2","CLN12_3","CLN12_4"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN3_Lux1","CLN3_Lux1","CLN3_Lux1","CLN3_Lux1",
                         "CLN3_Lux2","CLN3_Lux2","CLN3_Lux2","CLN3_Lux2",
                         "CLN12","CLN12","CLN12","CLN12"
                         ))
replicate <- c(1,2,3,4,
               1,2,3,4,
               1,2,3,4,
               1,2,3,4)

experiment <- rep("Brains", 16)
Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```

## Outliers removed
```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2","lfq_wt_3", "lfq_wt_4",
              "lfq_cln3_lux1_1", "lfq_cln3_lux1_2", "lfq_cln3_lux1_4",
              "lfq_cln3_lux2_1","lfq_cln3_lux2_2", "lfq_cln3_lux2_3", "lfq_cln3_lux2_4",
              "lfq_cln12_1","lfq_cln12_2", "lfq_cln12_3")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN3_Lux1_1", "CLN3_Lux1_2", "CLN3_Lux1_4",
                       "CLN3_Lux2_1", "CLN3_Lux2_2", "CLN3_Lux2_3","CLN3_Lux2_4",
                       "CLN12_1","CLN12_2","CLN12_3"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN3_Lux1","CLN3_Lux1","CLN3_Lux1",
                         "CLN3_Lux2","CLN3_Lux2","CLN3_Lux2","CLN3_Lux2",
                         "CLN12","CLN12","CLN12"
                         ))
replicate <- c(1,2,3,4,
               1,2,4,
               1,2,3,4,
               1,2,3)

experiment <- rep("Brains", length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing_Out.xlsx"))

```
# CLN3 only

```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2", "lfq_wt_3","lfq_wt_4",
              "lfq_cln3_lux1_1", "lfq_cln3_lux1_2","lfq_cln3_lux1_3", "lfq_cln3_lux1_4",
              "lfq_cln3_lux2_1","lfq_cln3_lux2_2", "lfq_cln3_lux2_3", "lfq_cln3_lux2_4")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN3_Lux1_1", "CLN3_Lux1_2", "CLN3_Lux1_3","CLN3_Lux1_4",
                       "CLN3_Lux2_1","CLN3_Lux2_2", "CLN3_Lux2_3","CLN3_Lux2_4"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN3_Lux1","CLN3_Lux1","CLN3_Lux1","CLN3_Lux1",
                         "CLN3_Lux2","CLN3_Lux2","CLN3_Lux2","CLN3_Lux2"
                         ))
replicate <- c(1,2,3,4,
               1,2,3,4,
               1,2,3,4)

experiment <- rep("Brains", 12)
Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```

## Outliers removed
```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2","lfq_wt_3", "lfq_wt_4",
              "lfq_cln3_lux1_1", "lfq_cln3_lux1_2", "lfq_cln3_lux1_4",
              "lfq_cln3_lux2_2", "lfq_cln3_lux2_3", "lfq_cln3_lux2_4")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN3_Lux1_1", "CLN3_Lux1_2", "CLN3_Lux1_4",
                       "CLN3_Lux2_2", "CLN3_Lux2_3","CLN3_Lux2_4"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN3_Lux1","CLN3_Lux1","CLN3_Lux1",
                         "CLN3_Lux2","CLN3_Lux2","CLN3_Lux2"
                         ))
replicate <- c(1,2,3,4,
               1,2,4,
               2,3,4
               )

experiment <- rep("Brains", length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing_Out.xlsx"))

```

# CLN12 only


```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN12_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2", "lfq_wt_3","lfq_wt_4",
              "lfq_cln12_1","lfq_cln12_2", "lfq_cln12_3", "lfq_cln12_4")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN12_1","CLN12_2","CLN12_3","CLN12_4"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN12","CLN12","CLN12","CLN12"
                         ))
replicate <- c(1,2,3,4,
               1,2,3,4)

experiment <- rep("Brains", 8)
Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```

## Outliers removed
```{r}
# Experiment design ####
# You just need modify script in Experiment heading


#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT", "CLN3_Lux1_vs_CLN3_Lux2", "CLN3_Lux1_vs_CLN12", "CLN3_Lux2_vs_CLN12")
comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT", "CLN12_vs_WT")

#comparisons <- c("CLN3_Lux1_vs_WT","CLN3_Lux2_vs_WT")
#comparisons <- c("CLN12_vs_WT")
#comparisons <- c("CLN3_Lux1_vs_WT")

label <-    c("lfq_wt_1", "lfq_wt_2","lfq_wt_3", "lfq_wt_4",
              "lfq_cln3_lux1_1", "lfq_cln3_lux1_2", "lfq_cln3_lux1_4",
              "lfq_cln3_lux2_1","lfq_cln3_lux2_2", "lfq_cln3_lux2_3", "lfq_cln3_lux2_4",
              "lfq_cln12_1","lfq_cln12_2", "lfq_cln12_3")

label_columns <-  label

columns_to_rename <- c("WT_1", "WT_2","WT_3", "WT_4",
                       "CLN3_Lux1_1", "CLN3_Lux1_2", "CLN3_Lux1_4",
                       "CLN3_Lux2_1", "CLN3_Lux2_2", "CLN3_Lux2_3","CLN3_Lux2_4",
                       "CLN12_1","CLN12_2","CLN12_3"
                       )


condition <- as.factor(c("WT","WT","WT","WT",
                         "CLN3_Lux1","CLN3_Lux1","CLN3_Lux1",
                         "CLN3_Lux2","CLN3_Lux2","CLN3_Lux2","CLN3_Lux2",
                         "CLN12","CLN12","CLN12"
                         ))
replicate <- c(1,2,3,4,
               1,2,4,
               1,2,3,4,
               1,2,3)

experiment <- rep("Brains", length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing_Out.xlsx"))

```


# 3. Data Cleaning

```{r}

data_cleaning(prot_data_brain, Exp_design, comparisons, output_path)



```


# 4. Data Analysis
```{r}
# Load desired imputation file
data_analysis(mixed_imputation, Exp_design, comparisons, output_path)

```


# 5. Plots
```{r}
#Change to 1 to print Barplots
print_barplots <- 0

source("../code/05_Plots.R")

```

# 6. GO
```{r}
#Use upregulated and downregulated genes independently
independent_UPDOWN <- 0
#Select type of ontology
ont <- "ALL" #Modify to "BP", "MF" or "CC" on base of your needs

source("../code/06_GO.R")
```

# 7. Strings
```{r}
independent_UPDOWN <- 1
source("../code/07_Strings.R")
```


# 8. gseGO & KEGG
```{r}
source("../code/08_gseGO.R")

source("../code/09_gseKEGG.R")

```

# 10. RBioAPI String and Panther
```{r}
source("../code/10_RBioApi_string.R") 
source("../code/11_RBioApi_panther.R")
```

# 11. Adj

```{r}
source("../code/13_GO_padj.R")

source("../code/15_gseGO_adj.R")
source("../code/13_gseKEGG_padj.R")


```





```{r}
data_cleaning(prot_data_brain, Exp_design, comparisons, output_path)
# Load desired imputation file
data_analysis(mixed_imputation, Exp_design, comparisons, output_path)
#Change to 1 to print Barplots
print_barplots <- 0
source("../code/05_Plots.R")
#Use upregulated and downregulated genes independently
independent_UPDOWN <- 0
#Select type of ontology
ont <- "ALL" #Modify to "BP", "MF" or "CC" on base of your needs
source("../code/06_GO.R")
independent_UPDOWN <- 1
source("../code/07_Strings.R")
source("../code/08_gseGO.R")
#source("../code/09_gseKEGG.R")
source("../code/13_GO_padj.R")
source("../code/15_gseGO_adj.R")
#source("../code/13_gseKEGG_padj.R")

```

