
# 1. Importing data

## Loading functions
```{r}
rm(list=ls())
gc()

output_path <- "./output/Clara_WT_APP/AllData/"
output_path <- "./output/Clara_WT_APP/outlier_removed/"
output_path <- "./output/Clara_WT_APP/outlier_removed/MinProb_2_3_4/"

```

```{r}
image_number <- 1
kegg_organism = "mmu"#dre for Danio rerio, hsa for Homo sapiens, mmu for Mus musculus
species <- 10090 #9606 for Human, 10090 for mouse, 7955 for zebrafish
organism <- "org.Mm.eg.db" #"org.Hs.eg.db"
```


```{r}
source("../code/global_variables.R")
source("../code/01_loading_data.R")
source("../code/03_cleaning_data.R")
source("../code/04_data_analysis.R")
```



```{r}
# Select input data file
prot_data <- readxl::read_xlsx(path = "../rawdata/021425_LFQ_Astrocitos_exvivo_Santi.xlsx",sheet = "LFQ")
loading_data(prot_data)

```

# 2. Experiment Design
```{r}
# Experiment design ####
# You just need modify script in Experiment heading
comparisons <- c("APP_vs_WT")

label <- c("lfq_WT1","lfq_WT2","lfq_WT3","lfq_WT4",
           "lfq_APP1", "lfq_APP2", "lfq_APP3", "lfq_APP4")

label_columns <- label
columns_to_rename <- c("WT_1","WT_2","WT_3","WT_4",
           "APP_1", "APP_2", "APP_3", "APP_4")

condition <- as.factor(c("WT","WT","WT","WT",
                         "APP","APP","APP","APP"))
replicate <- c(1,2,3,4,
               1,2,3,4)


experiment <- rep("Astrocytes_APP",length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)
Exp_design


print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```

## Outliers Removed
```{r eval=FALSE, include=FALSE}

# Experiment design ####
# You just need modify script in Experiment heading
comparisons <- c("APP_vs_WT")

label <- c("lfq_WT1","lfq_WT3","lfq_WT4",
           "lfq_APP1", "lfq_APP3", "lfq_APP4")

label_columns <- label

columns_to_rename <- c("WT_1","WT_3","WT_4",
                        "APP_1", "APP_3", "APP_4")

condition <- as.factor(c("WT","WT","WT",
                         "APP","APP","APP"))
replicate <- c(1,3,4,
               1,3,4)


experiment <- rep("Astrocytes_APP",length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate,columns_to_rename, experiment)
Exp_design


print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```
# 3. Data Cleaning

```{r}
#source("../code/03_cleaning_data.R")
#data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var = "MinProb")
#data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var = "MinProb")

#data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var="zero",val_man = TRUE, value_imputation = 0.1)
#data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var="zero",val_man = FALSE)

#data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var = "QRILC")

source("../code/03_cleaning_data_mixed_imputation.R")

data_cleaning(prot_data, Exp_design, comparisons, output_path, mnar_var="zero")
```


# 4. Data Analysis
```{r}
# Load desired imputation file

#data_analysis(data_imp, Exp_design, comparisons, output_path)
#data_analysis(data_imp_man, Exp_design, comparisons, output_path)

data_analysis(mixed_imputation, Exp_design, comparisons, output_path)
```


# 5. Plots
```{r}
#Change to 1 to print Barplots
print_barplots <- 0

source("../code/05_Plots.R")

```

# 6. GO
```{r}
#Use upregulated and downregulated genes independently
independent_UPDOWN <- 1
#Select type of ontology
ont <- "ALL"  # Can be "ALL", "BP", "CC", or "MF"
source("../code/06_GO.R")

```

# 7. Strings
```{r}
independent_UPDOWN <- 1
source("../code/07_Strings.R")
```


# 8. gseGO & KEGG
```{r}
#Use upregulated and downregulated genes independently
independent_UPDOWN <- 1
#Select type of ontology
ont <- "ALL"  # Can be "ALL", "BP", "CC", or "MF"
source("../code/08_gseGO.R")
```


```{r}
source("../code/09_gseKEGG.R")

```

# 10. RBioAPI String and Panther
```{r}
source("../code/10_RBioApi_string.R") 
source("../code/11_RBioApi_panther.R")
```

# 11. Adj

```{r}
source("../code/13_GO_padj.R")

source("../code/15_gseGO_adj.R")
source("../code/13_gseKEGG_padj.R")


```

