

# 1. Importing data

## Loading functions
```{r}
output_path <- "./output/IP_CLN3_PXD031582/"
#output_path <- "./output/IP_CLN3_PXD031582/outliers_removed/"


source("../code/global_variables.R")
source("../code/01_loading_data.R")
source("../code/03_cleaning_data.R")
source("../code/04_data_analysis.R")



```


```{r}
# Select input data file
prot_data <- readxl::read_xlsx(path = "../rawdata/ProteinGroups_Project_PXD031582.xlsx")
loading_data(prot_data)

```
# 2. Experiment Design
## IP_CLN3 Experiment design
```{r}
# Experiment design ####
# You just need modify script in Experiment heading

comparisons <- c("CTRL_vs_WT","CTRL_vs_KO", "KO_vs_WT")


label <-    c("LFQ intensity CTRL_01", "LFQ intensity CTRL_02", "LFQ intensity CTRL_03", "LFQ intensity CTRL_04",              
              "LFQ intensity TMEM_CLN3_KO_01", "LFQ intensity TMEM_CLN3_KO_02", "LFQ intensity TMEM_CLN3_KO_03", 
              "LFQ intensity TMEM_CLN3_KO_04", "LFQ intensity TMEM_CLN3_WT_01", "LFQ intensity TMEM_CLN3_WT_02", 
              "LFQ intensity TMEM_CLN3_WT_03", "LFQ intensity TMEM_CLN3_WT_04") 

label_columns <-  label

columns_to_rename <- c("CTRL_1", "CTRL_2", "CTRL_3", "CTRL_4",
                       "KO_1", "KO_2", "KO_3", "KO_4",
                       "WT_1","WT_2","WT_3", "WT_4")

condition <- as.factor(c("CTRL", "CTRL", "CTRL", "CTRL",
                         "KO", "KO", "KO", "KO",
                         "WT","WT","WT", "WT"))

replicate <- c(1,2,3,4,
               1,2,3,4,
               1,2,3,4)

experiment <- rep("Lyso_IP_cln3",length(replicate))

Exp_design <- cbind.data.frame(label,condition,replicate, columns_to_rename, experiment)
Exp_design

print(Exp_design)

Exp_design %>% 
  write_xlsx(paste0(output_path,"tables/experiment_desing.xlsx"))

```
### Outliers removed


# 3. Data Cleaning

```{r}

data_cleaning(prot_data, Exp_design, comparisons, output_path)



```


# 4. Data Analysis
```{r}
# Load desired imputation file
data_analysis(mixed_imputation, Exp_design, comparisons, output_path)

```


# 5. Plots
```{r}
#Change to 1 to print Barplots
print_barplots <- 0

source("../code/05_Plots.R")

```

# 6. GO
```{r}
#Use upregulated and downregulated genes independently
independent_UPDOWN <- 0
#Select type of ontology
ont <- "BP"  # Can be "ALL", "BP", "CC", or "MF"
source("../code/06_GO.R")
```

# 7. Strings
```{r}
source("../code/07_Strings.R")
```


# 8. gseGO & KEGG
```{r}
source("../code/08_gseGO.R")

source("../code/09_gseKEGG.R")

```

# 10. RBioAPI String and Panther
```{r}
source("../code/10_RBioApi_string.R") 
source("../code/11_RBioApi_panther.R")
```

# 11. Adj

```{r}
source("../code/13_GO_padj.R")

source("../code/15_gseGO_adj.R")
source("../code/13_gseKEGG_padj.R")


```