---
title: "Venn Diagrams"
output: html_document
date: "2024-04-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Libraries
library(tidyverse)
library(readxl)
library(psych)
library(DescTools)
library(car)
library(stats)
library(broom)
library(dunn.test)
library(stats)
library(ggpubr)
library(rstatix)
library(ggVennDiagram)
library(ggvenn)
library(VennDiagram)
library(gridExtra)
library(openxlsx)
```

# pval
```{r}
#Load document
pval_data <- read_xlsx("../rawdata/20241021_Venn_diagrams.xlsx", sheet = "pval_human" )

pval_data <- read_xlsx("../rawdata/Venn_diagrams.xlsx", sheet = "padj_human_altered" )

  pval_data <- read_xlsx("../rawdata/dif_genes.xlsx", sheet = "Diffgenes genenames" )

```

# all columns
```{r}
# Convert each column to a list
#all columns

list_pval <- pval_data %>%
  imap(~ list(na.omit(.x))) %>%
  unlist(recursive = FALSE)
names(list_pval) <- colnames(pval_data)
```
# Comparisons list creation
## UP & DOWN
```{r}

larvae_pval_CLN4_NTC_UP <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt", "CLN4_L115_NTC", "CLN4_L116_NTC") 

larvae_pval_CLN4_NTC_DOWN <- c("Larvae_WT_CLN3_Lux1", "Larvae_WT_CLN3_Lux2", "Larvae_WT_CLN12", "CLN4_NTC_L115R", "CLN4_NTC_L116")

brain_pval_CLN4_NTC_UP <- c("Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt",  "CLN4_L115_NTC", "CLN4_L116_NTC")

brain_pval_CLN4_NTC_DOWN <- c("Brain_WT_CLN3_Lux1", "Brain_WT_CLN3_Lux2", "Brain_WT_CLN12", "CLN4_NTC_L115R", "CLN4_NTC_L116")


larvae_pval_CLN4_WT_UP <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt", "CLN4_L115_WT", "CLN4_L116_WT")

larvae_pval_CLN4_WT_DOWN <- c("Larvae_WT_CLN3_Lux1", "Larvae_WT_CLN3_Lux2", "Larvae_WT_CLN12", "CLN4_WT_L115R", "CLN4_WT_L116")

brain_pval_CLN4_WT_UP <- c("Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt", "CLN4_L115_WT", "CLN4_L116_WT")

brain_pval_CLN4_WT_DOWN <- c("Brain_WT_CLN3_Lux1", "Brain_WT_CLN3_Lux2", "Brain_WT_CLN12", "CLN4_WT_L115R", "CLN4_WT_L116")

brain_larvae_UP <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt","Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt")

brain_larvae_DOWN <- c("Brain_WT_CLN3_Lux1", "Brain_WT_CLN3_Lux2", "Brain_WT_CLN12","Larvae_WT_CLN3_Lux1", "Larvae_WT_CLN3_Lux2", "Larvae_WT_CLN12")

CLN3_CLN12_CLN4 <- c()
```

```{r}
# Función para extraer listas de genes basado en nombres de columnas
get_gene_lists <- function(df, column_names) {
  gene_lists <- lapply(column_names, function(col) df[[col]])
   names(gene_lists) <- column_names  # Asignar nombres a cada elemento de la lista
  return(gene_lists)
}
```


```{r}
# Generar listas de genes para cada conjunto
list_larvae_pval_CLN4_NTC_UP <- get_gene_lists(pval_data, larvae_pval_CLN4_NTC_UP)
list_larvae_pval_CLN4_NTC_DOWN <- get_gene_lists(pval_data, larvae_pval_CLN4_NTC_DOWN)
list_brain_pval_CLN4_NTC_UP <- get_gene_lists(pval_data, brain_pval_CLN4_NTC_UP)
list_brain_pval_CLN4_NTC_DOWN <- get_gene_lists(pval_data, brain_pval_CLN4_NTC_DOWN)
list_larvae_pval_CLN4_WT_UP <- get_gene_lists(pval_data, larvae_pval_CLN4_WT_UP)
list_larvae_pval_CLN4_WT_DOWN <- get_gene_lists(pval_data, larvae_pval_CLN4_WT_DOWN)
list_brain_pval_CLN4_WT_UP <- get_gene_lists(pval_data, brain_pval_CLN4_WT_UP)
list_brain_pval_CLN4_WT_DOWN <- get_gene_lists(pval_data, brain_pval_CLN4_WT_DOWN)
list_brain_larvae_UP <- get_gene_lists(pval_data, brain_larvae_UP)
list_brain_larvae_DOWN <- get_gene_lists(pval_data, brain_larvae_DOWN)



```

```{r}
lists_Venn <- c("list_larvae_pval_CLN4_NTC_UP", "list_larvae_pval_CLN4_NTC_DOWN", 
                "list_brain_pval_CLN4_NTC_UP" , "list_brain_pval_CLN4_NTC_DOWN", 
                "list_larvae_pval_CLN4_WT_UP", "list_larvae_pval_CLN4_WT_DOWN", 
                "list_brain_pval_CLN4_WT_UP", "list_brain_pval_CLN4_WT_DOWN",
                "list_brain_larvae_UP", "list_brain_larvae_DOWN")
```



# Altered genes

```{r}

larvae_pval_CLN4_NTC <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt", "CLN4_L115_NTC", "CLN4_L116_NTC") 


brain_pval_CLN4_NTC <- c("Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt",  "CLN4_L115_NTC", "CLN4_L116_NTC")


larvae_pval_CLN4_WT <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt", "CLN4_L115_WT", "CLN4_L116_WT")


brain_pval_CLN4_WT <- c("Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt", "CLN4_L115_WT", "CLN4_L116_WT")

brain_larvae <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt","Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt")

brain <- c("Brain_CLN3_Lux1_wt", "Brain_CLN3_Lux2_wt", "Brain_CLN12_wt")
larvae <- c("Larvae_CLN3_Lux1_wt", "Larvae_CLN3_Lux2_wt", "Larvae_CLN12_wt")

CLN4_NTC <- c("CLN4_L115_NTC", "CLN4_L116_NTC")


CLN4_WT <- c("CLN4_L115_WT", "CLN4_L116_WT")

```

```{r}
CLN4 <- c("Hs_genename_L115R",	"Hs_genename_L116",	"Hs_genename_L115_CA3",	"Hs_genename_L116_CA3")

ZF <- c("Hs_genename_Br_Lux1",	"Hs_genename_Br_Lux2",	"Hs_genename_Br_CLN12",	"Hs_genename_Lv_Lux1",	"Hs_genename_Lv_Lux2",	"Hs_genename_Lv_CLN12")

Brain <- c("Hs_genename_Br_Lux1",	"Hs_genename_Br_Lux2",	"Hs_genename_Br_CLN12")
Larvae <- c("Hs_genename_Lv_Lux1",	"Hs_genename_Lv_Lux2",	"Hs_genename_Lv_CLN12")


Brain_CLN4 <- c("Hs_genename_L115_CA3"	,"Hs_genename_L116_CA3",	"Hs_genename_Br_Lux1",	"Hs_genename_Br_Lux2",	"Hs_genename_Br_CLN12")
Larvae_CLN4 <- c("Hs_genename_Lv_Lux1",	"Hs_genename_Lv_Lux2",	"Hs_genename_Lv_CLN12")

all_lists <- c("Hs_genename_L115R",	"Hs_genename_L116",	"Hs_genename_L115_CA3",	"Hs_genename_L116_CA3",	"Hs_genename_Br_Lux1",	"Hs_genename_Br_Lux2",	"Hs_genename_Br_CLN12",	"Hs_genename_Lv_Lux1",	"Hs_genename_Lv_Lux2",	"Hs_genename_Lv_CLN12")

```

```{r}
# Función para extraer listas de genes basado en nombres de columnas
get_gene_lists <- function(df, column_names) {
  gene_lists <- lapply(column_names, function(col) df[[col]])
   names(gene_lists) <- column_names  # Asignar nombres a cada elemento de la lista
  return(gene_lists)
}
```


```{r}
# Generar listas de genes para cada conjunto
list_larvae_pval_CLN4_NTC <- get_gene_lists(pval_data, larvae_pval_CLN4_NTC)
list_brain_pval_CLN4_NTC <- get_gene_lists(pval_data, brain_pval_CLN4_NTC)
list_larvae_pval_CLN4_WT <- get_gene_lists(pval_data, larvae_pval_CLN4_WT)
list_brain_pval_CLN4_WT <- get_gene_lists(pval_data, brain_pval_CLN4_WT)
list_brain_larvae <- get_gene_lists(pval_data, brain_larvae)
list_brain <- get_gene_lists(pval_data, brain)
list_larvae <- get_gene_lists(pval_data, larvae)
list_CLN4_NTC <- get_gene_lists(pval_data, CLN4_NTC)
list_CLN4_WT <- get_gene_lists(pval_data, CLN4_WT)

```
```{r}
# Generar listas de genes para cada conjunto
list_larvae_CLN4 <- get_gene_lists(pval_data, Larvae_CLN4)
list_brain_CLN4 <- get_gene_lists(pval_data, Brain_CLN4)
list_CLN4 <- get_gene_lists(pval_data, CLN4)
list_ZF <- get_gene_lists(pval_data, ZF)
list_Brain <- get_gene_lists(pval_data, Brain)
list_Larvae <- get_gene_lists(pval_data, Larvae)
list_all_lists <- get_gene_lists(pval_data, all_lists)

lists_Venn <- c("list_larvae_CLN4", "list_brain_CLN4", "list_CLN4", "list_ZF", "list_all_lists", "list_Brain", "list_Larvae")
```

```{r}
lists_Venn <- c("list_larvae_pval_CLN4_NTC", 
                "list_brain_pval_CLN4_NTC" , 
                "list_larvae_pval_CLN4_WT", 
                "list_brain_pval_CLN4_WT", 
                "list_brain_larvae",
                "list_brain",
                "list_larvae",
                "list_CLN4_NTC", 
                "list_CLN4_WT")
```

# List Creation

```{r}
# Crear un objeto 'all_gene_lists' usando los nombres en 'lists_Venn'
all_gene_lists <- lapply(lists_Venn, function(name) get(name))

# Asignar nombres a 'all_gene_lists' para usar en el diagrama de Venn
names(all_gene_lists) <- lists_Venn
```


```{r}
# Function to remove NA values from a list
remove_na_genes <- function(gene_list) {
  lapply(gene_list, function(sublist) sublist[!is.na(sublist)])
}

# Apply the function to each second-level list in all_gene_lists
all_gene_lists <- lapply(all_gene_lists, remove_na_genes)



```

# Plot
```{r}
#venn
library(venn)
library(ggpolypath)

venn_plot <- function(gene_lists, list_name){
    # Remover NAs de cada lista
  gene_lists <- lapply(gene_lists, remove_na_genes)
  
  # Crear el diagrama de Venn usando Venn
  ggvenn_plot <- venn(gene_lists, ggplot = TRUE,zcolor =c("#E41A1C", "#377EB8", "#4DAF4A", "#984EA3", "#FF7F00"), ilabels = "counts", ilcs = 1.2, box = FALSE, borders = TRUE) 
  
  # Guardar el diagrama de Venn como PDF
  pdf_filename <- paste0("output/Venn_diagram/", list_name, "_venn_diagram.pdf")
  ggsave(pdf_filename, plot = ggvenn_plot, device = "pdf", dpi = 300, width = 7, height = 7, units = "in")
  
  # Guardar el diagrama de Venn como TIFF
  tiff_filename <- paste0("output/Venn_diagram/", list_name, "_venn_diagram.tiff")
  ggsave(tiff_filename, plot = ggvenn_plot, device = "tiff", dpi = 300, width = 7, height = 7, units = "in")
  
  # Mostrar el diagrama de Venn
  print(ggvenn_plot)
  
  return(ggvenn_plot)  # Devolver el plot para almacenar en una lista
}
```

```{r}
venn_plots <- lapply(names(all_gene_lists), function(list_name) {
  venn_plot(all_gene_lists[[list_name]], list_name)
})
```




# Cross-tables

```{r}
# Función para calcular todas las intersecciones posibles de genes sin NAs
calculate_all_intersections <- function(gene_lists, list_name) {
  # Remover NAs de cada lista
  gene_lists <- lapply(gene_lists, remove_na_genes)
  
  # Inicializar una lista para almacenar datos de intersección
  intersection_data <- list()
  
  # Iterar sobre todos los tamaños posibles de combinaciones (desde 1 a N)
  for (n in 1:length(gene_lists)) {
    # Generar todas las combinaciones posibles de tamaño n
    combinations <- combn(seq_along(gene_lists), n, simplify = FALSE)
    
    # Calcular intersecciones para cada combinación
    intersections_n <- lapply(combinations, function(comb) {
      intersection_name <- paste(names(gene_lists)[comb], collapse = "_AND_")
      intersection_genes <- Reduce(intersect, gene_lists[comb])
      num_genes <- length(intersection_genes)  # Calcular el número de genes en la intersección
      return(list(name = intersection_name, genes = intersection_genes, num_genes = num_genes))
    })
    
    # Agregar las intersecciones de tamaño n a la lista de datos de intersección
    intersection_data <- c(intersection_data, intersections_n)
  }
  
  # Convertir las intersecciones en un dataframe
  intersection_df <- data.frame(
    List_Name = list_name,
    Intersection = sapply(intersection_data, function(x) x$name),
    Genes = sapply(intersection_data, function(x) paste(x$genes, collapse = ", ")),
    Num_Genes = sapply(intersection_data, function(x) x$num_genes)
  )
  
  return(intersection_df)
}

# Aplicar la función calculate_all_intersections a cada sublista del nivel 2 en all_gene_lists
all_intersection_dfs <- lapply(names(all_gene_lists), function(list_name) {
  calculate_all_intersections(all_gene_lists[[list_name]], list_name)
})
# Asignar nombres a 'all_gene_lists' para usar en el diagrama de Venn
names(all_intersection_dfs) <- lists_Venn
# Combinar todos los dataframes de intersecciones en un solo dataframe
final_intersection_df <- do.call(rbind, all_intersection_dfs)

# Mostrar el dataframe final de intersecciones
print(final_intersection_df)

# Exportar el dataframe a un archivo CSV
write.csv(final_intersection_df, "output/Venn_diagram/intersections_genes.csv", row.names = FALSE)

```

# Upset plot 

```{r}
library(genekitr)


upset <- function(list, list_name){
  upset_plot <- plotVenn(list,
         use_venn = FALSE,
         main_text_size = 15,
         legend_text_size = 7,
         legend_position = 'left'
)

   # Guardar el diagrama de Venn como PDF
  pdf_filename <- paste0("output/Venn_diagram/", list_name, "_upset.pdf")
  ggsave(pdf_filename, plot = upset_plot, device = "pdf", dpi = 300, width = 10, height = 7, units = "in")
  
  # Guardar el diagrama de Venn como TIFF
  tiff_filename <- paste0("output/Venn_diagram/", list_name, "_upset.tiff")
  ggsave(tiff_filename, plot = upset_plot, device = "tiff", dpi = 300, width = 10, height = 7, units = "in")
  
  print(upset_plot)
  return(upset_plot)
}
venn_plots <- lapply(names(all_gene_lists), function(list_name) {
  upset(all_gene_lists[[list_name]], list_name)
})


```

```{r}
# Load necessary libraries
library(dplyr)
library(tidyr)


overlap_genes <- function(gene_list, list_name){
# Convert the list to a data frame suitable for ComplexUpset
gene_df <- data.frame(
  gene = unique(unlist(gene_list))
)

# Dynamically add columns for each set in gene_df
for (set_name in names(gene_list)) {
  gene_df[[set_name]] <- gene_df$gene %in% gene_list[[set_name]]
}

# Identify set columns dynamically
set_columns <- names(gene_df)[-1]  # All columns except 'gene'

# Calculate intersection data using pivot_longer and dplyr
intersection_data <- gene_df %>%
  pivot_longer(cols = all_of(set_columns), names_to = "set", values_to = "present") %>%
  filter(present) %>%
  group_by(gene) %>%
  summarize(intersection = paste(set, collapse = "&"), .groups = 'drop')

# Calculate intersections with fewer than 10 genes for annotation
intersection_counts <- intersection_data %>%
  count(intersection) 

# Annotate genes over bars for intersections with fewer than 10 genes
gene_text_df <- intersection_data %>%
  semi_join(intersection_counts, by = "intersection") %>%
  group_by(intersection) %>%
  summarize(
    gene_text = paste(gene, collapse = ", "),
    num_genes = n(),
    .groups = 'drop'
  )

# Print the final data frame
print(gene_text_df)
}

overlapped_genes <- lapply(names(all_gene_lists), function(list_name) {
  overlap_genes(all_gene_lists[[list_name]], list_name)
})

# Asignar nombres a 'all_gene_lists' para usar en el diagrama de Venn
names(overlapped_genes) <- lists_Venn


# Crear un objeto workbook
wb <- createWorkbook()

# Agregar cada dataframe a una hoja
for(name in lists_Venn) {
  addWorksheet(wb, sheetName = name)
  writeData(wb, sheet = name, x = overlapped_genes[[name]])
}

# Guardar el archivo Excel
saveWorkbook(wb, file = "output.xlsx", overwrite = TRUE)

```

